DROP TABLE bet_option_auto_reduce_odds IF EXISTS;
DROP TABLE bet_option_water_level IF EXISTS;
DROP TABLE draw_bet_option_result IF EXISTS;
DROP TABLE draw_bet_option_value_result IF EXISTS;
DROP TABLE draw_result IF EXISTS;
DROP TABLE handicap IF EXISTS;
DROP TABLE handicap_bet_option IF EXISTS;
DROP TABLE handicap_bet_option_config IF EXISTS;
DROP TABLE handicap_bet_option_value IF EXISTS;
DROP TABLE handicap_config IF EXISTS;
DROP TABLE handicap_play_method IF EXISTS;
DROP TABLE handicap_play_method_algorithm IF EXISTS;
DROP TABLE handicap_play_method_config IF EXISTS;
DROP TABLE sub_handicap IF EXISTS;
CREATE TABLE bet_option_auto_reduce_odds
(
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_option_id bigint,
  water_level   int,
  reduce_odds   varchar(10),
  lowest_odds   varchar(10),
  PRIMARY KEY (id)
);
CREATE TABLE bet_option_water_level
(
  bet_option_id bigint GENERATED BY DEFAULT AS IDENTITY,
  water_level   int,
  odds          varchar(10),
  PRIMARY KEY (bet_option_id)
);
CREATE TABLE draw_bet_option_result
(
  id              bigint GENERATED BY DEFAULT AS IDENTITY,
  lottery_id      bigint,
  lottery_name    varchar(64),
  handicap_id     bigint,
  sub_handicap_id bigint,
  play_method_id  bigint,
  draw_id         bigint,
  issue_number    varchar(32),
  draw_number     varchar(64),
  bet_option_id   bigint,
  bet_option_name varchar(32),
  seat_number     int,
  draw_time       datetime,
  create_time     datetime,
  PRIMARY KEY (id)
);
CREATE TABLE draw_bet_option_value_result
(
  id                        bigint GENERATED BY DEFAULT AS IDENTITY,
  draw_bet_option_result_id bigint,
  bet_option_value          varchar(32),
  PRIMARY KEY (id)
);
CREATE TABLE draw_result
(
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  lottery_id   bigint,
  handicap_id  bigint      NOT NULL,
  lottery_name varchar(64),
  issue_number varchar(32) NOT NULL,
  status       varchar(16),
  num          int,
  create_time  datetime,
  modify_time  datetime,
  draw_number  varchar(32),
  PRIMARY KEY (id)
);
CREATE TABLE handicap
(
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  lottery_id   bigint,
  lottery_name varchar(32),
  issue_number varchar(32),
  max_limit    varchar(10) NOT NULL,
  status       varchar(32),
  sort         int,
  create_time  datetime,
  modify_time  datetime,
  ver          int,
  PRIMARY KEY (id)
);
CREATE TABLE handicap_bet_option
(
  id               bigint GENERATED BY DEFAULT AS IDENTITY,
  play_method_id   bigint,
  bet_option_id    bigint,
  alias            varchar(32),
  name             varchar(32),
  combination_up   int,
  combination_down int,
  odds             varchar(10),
  status           varchar(16),
  bet_option_type  varchar(32),
  sort             int,
  create_time      datetime,
  modify_time      datetime,
  PRIMARY KEY (id)
);
CREATE TABLE handicap_bet_option_config
(
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_option_id bigint,
  config_option varchar(32),
  config_value  varchar(128),
  status        varchar(16),
  summary       varchar(128),
  PRIMARY KEY (id)
);
CREATE TABLE handicap_bet_option_value
(
  id                  bigint GENERATED BY DEFAULT AS IDENTITY,
  bet_option_id       bigint,
  bet_option_value_id bigint,
  bet_option_value    varchar(64),
  status              varchar(16),
  sort                int,
  PRIMARY KEY (id)
);
CREATE TABLE handicap_config
(
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  handicap_id   bigint,
  config_option varchar(32),
  config_value  varchar(128),
  status        varchar(16),
  summary       varchar(128),
  PRIMARY KEY (id)
);
CREATE TABLE handicap_play_method
(
  id                      bigint GENERATED BY DEFAULT AS IDENTITY,
  pre_id                  bigint,
  play_method_id          bigint,
  play_method_category_id bigint,
  sub_handicap_id         bigint,
  short_code              varchar(64),
  name                    varchar(32),
  status                  varchar(16),
  type                    varchar(16),
  redeem_type             varchar(32),
  create_time             datetime,
  modify_time             datetime,
  summary                 varchar(128),
  PRIMARY KEY (id)
);
CREATE TABLE handicap_play_method_algorithm
(
  id              bigint GENERATED BY DEFAULT AS IDENTITY,
  play_method_id  bigint,
  name            varchar(32),
  short_code      varchar(32),
  annotation_code varchar(32),
  mq_topic        varchar(64),
  url             varchar(128),
  type            varchar(16),
  status          varchar(16),
  summary         varchar(128),
  PRIMARY KEY (id)
);
CREATE TABLE handicap_play_method_config
(
  id                      bigint GENERATED BY DEFAULT AS IDENTITY,
  handicap_play_method_id bigint,
  config_option           varchar(32),
  config_value            varchar(128),
  status                  varchar(16),
  summary                 varchar(128),
  PRIMARY KEY (id)
);
CREATE TABLE sub_handicap
(
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  handicap_id  bigint,
  name         varchar(32),
  issue_number varchar(32),
  status       varchar(16),
  sort         int,
  create_time  datetime,
  modify_time  datetime,
  PRIMARY KEY (id)
);
CREATE INDEX bet_option_auto_reduce_odds_bet_option_id ON bet_option_auto_reduce_odds (bet_option_id);
CREATE INDEX draw_bet_option_result_lottery_id ON draw_bet_option_result (lottery_id);
CREATE INDEX draw_bet_option_result_handicap_id ON draw_bet_option_result (handicap_id);
CREATE INDEX draw_bet_option_result_sub_handicap_id ON draw_bet_option_result (sub_handicap_id);
CREATE INDEX draw_bet_option_result_play_method_id ON draw_bet_option_result (play_method_id);
CREATE INDEX draw_bet_option_result_draw_id ON draw_bet_option_result (draw_id);
CREATE INDEX draw_bet_option_result_issue_number ON draw_bet_option_result (issue_number);
CREATE INDEX draw_bet_option_result_draw_number ON draw_bet_option_result (draw_number);
CREATE INDEX draw_bet_option_result_bet_option_id ON draw_bet_option_result (bet_option_id);
CREATE INDEX draw_bet_option_value_result_draw_bet_option_result_id ON draw_bet_option_value_result (draw_bet_option_result_id);
CREATE INDEX draw_result_lottery_id ON draw_result (lottery_id);
CREATE INDEX draw_result_handicap_id ON draw_result (handicap_id);
CREATE INDEX draw_result_issue_number ON draw_result (issue_number);
CREATE INDEX handicap_lottery_id ON handicap (lottery_id);
CREATE INDEX handicap_issue_number ON handicap (issue_number);
CREATE INDEX handicap_bet_option_play_method_id ON handicap_bet_option (play_method_id);
CREATE INDEX handicap_bet_option_bet_option_id ON handicap_bet_option (bet_option_id);
CREATE INDEX handicap_bet_option_config_bet_option_id ON handicap_bet_option_config (bet_option_id);
CREATE INDEX handicap_bet_option_value_bet_option_id ON handicap_bet_option_value (bet_option_id);
CREATE INDEX handicap_bet_option_value_bet_option_value_id ON handicap_bet_option_value (bet_option_value_id);
CREATE INDEX handicap_config_handicap_id ON handicap_config (handicap_id);
CREATE INDEX handicap_play_method_pre_id ON handicap_play_method (pre_id);
CREATE INDEX handicap_play_method_play_method_id ON handicap_play_method (play_method_id);
CREATE INDEX handicap_play_method_play_method_category_id ON handicap_play_method (play_method_category_id);
CREATE INDEX handicap_play_method_sub_handicap_id ON handicap_play_method (sub_handicap_id);
CREATE INDEX handicap_play_method_short_code ON handicap_play_method (short_code);
CREATE INDEX handicap_play_method_algorithm_play_method_id ON handicap_play_method_algorithm (play_method_id);
CREATE INDEX handicap_play_method_algorithm_short_code ON handicap_play_method_algorithm (short_code);
CREATE INDEX handicap_play_method_config_handicap_play_method_id ON handicap_play_method_config (handicap_play_method_id);
CREATE INDEX sub_handicap_handicap_id ON sub_handicap (handicap_id);
CREATE INDEX sub_handicap_issue_number ON sub_handicap (issue_number);
