DROP TABLE "order" IF EXISTS;
DROP TABLE player IF EXISTS;
DROP TABLE player_account IF EXISTS;
DROP TABLE player_bank IF EXISTS;
DROP TABLE player_financial_account IF EXISTS;
DROP TABLE player_financial_detail IF EXISTS;
DROP TABLE player_lottery IF EXISTS;
DROP TABLE player_lottery_combination_option IF EXISTS;
DROP TABLE player_lottery_settle_bill IF EXISTS;
DROP TABLE player_summary IF EXISTS;
DROP TABLE withdrawal_bill IF EXISTS;

CREATE TABLE "order"
(
  id          bigint GENERATED BY DEFAULT AS IDENTITY,
  trade_code  varchar(64),
  player_id   bigint,
  order_no    varchar(64),
  ip          varchar(16),
  type        varchar(16),
  owner_type  varchar(25),
  status      varchar(16),
  amount      numeric(18, 4),
  create_time datetime,
  modify_time datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player
(
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  name         varchar(32),
  type         varchar(16),
  nick_name    varchar(32),
  promote_code varchar(32),
  qq           varchar(16),
  wechat       varchar(32),
  email        varchar(32),
  birthday     varchar(16),
  phone        varchar(20),
  status       varchar(16),
  create_time  datetime,
  modify_time  datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_account
(
  player_id    bigint      NOT NULL,
  account      varchar(32) NOT NULL,
  password     varchar(32),
  pay_password varchar(32),
  avatar       varchar(128),
  login_status varchar(32),
  PRIMARY KEY (player_id, account)
);
CREATE TABLE player_bank
(
  id             bigint GENERATED BY DEFAULT AS IDENTITY,
  player_id      bigint,
  bank_id        bigint,
  bank_name      varchar(32),
  bank_card_no   varchar(64),
  bank_card_name varchar(32),
  status         varchar(16),
  type           varchar(16),
  is_default     varchar(4),
  create_time    datetime,
  modify_time    datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_financial_account
(
  id          bigint GENERATED BY DEFAULT AS IDENTITY,
  account     varchar(32),
  player_id   bigint,
  amount      numeric(18, 4),
  status      varchar(16),
  type        varchar(16),
  create_time datetime,
  modify_time datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_financial_detail
(
  id                       bigint GENERATED BY DEFAULT AS IDENTITY,
  player_financial_id      bigint,
  player_financial_account varchar(32),
  trade_code               varchar(64),
  accounting_title         varchar(32),
  amount                   varchar(10),
  before_change_amount     varchar(10),
  after_change_amount      varchar(10),
  type                     varchar(16),
  settle_type              varchar(20),
  settle_no                varchar(32),
  opt_man                  varchar(32),
  opt_man_code             varchar(64),
  create_time              datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_lottery
(
  id                 bigint GENERATED BY DEFAULT AS IDENTITY,
  trade_code         varchar(64),
  player_id          bigint,
  order_id           bigint,
  handicap_id        bigint,
  sub_handicap_id    bigint,
  sub_handicap_name  varchar(32),
  lottery_id         bigint,
  lottery_name       varchar(32),
  play_method_id     bigint,
  play_method_name   varchar(32),
  bet_option_id      bigint,
  bet_value          varchar(32),
  seat_number        int,
  issue_number       varchar(32),
  principal          numeric(18, 4),
  num                int,
  odds               float,
  subsidiary_odds    float,
  status             varchar(16),
  type               varchar(16),
  owner_type         varchar(25),
  bet_type           varchar(16),
  redeem_type        varchar(32),
  draw_bet_option_id bigint,
  draw_number        varchar(32),
  draw_time          datetime,
  create_time        datetime,
  modify_time        datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_lottery_combination_option
(
  id                bigint GENERATED BY DEFAULT AS IDENTITY,
  player_lottery_id bigint,
  bet_option_id     bigint,
  combination_up    int,
  combination_down  int,
  index_start       int,
  index_end         int,
  sort              int,
  odds              varchar(10),
  PRIMARY KEY (id)
);
CREATE TABLE player_lottery_settle_bill
(
  id                       bigint GENERATED BY DEFAULT AS IDENTITY,
  trade_code               varchar(64),
  player_lottery_id        bigint,
  player_id                bigint,
  player_financial_account varchar(32),
  bill_no                  varchar(32),
  amount                   numeric(18, 4),
  status                   varchar(16),
  settle_type              varchar(16),
  type                     varchar(16),
  owner_type               varchar(25),
  draw_time                datetime,
  create_time              datetime,
  modify_time              datetime,
  PRIMARY KEY (id)
);
CREATE TABLE player_summary
(
  player_id   bigint GENERATED BY DEFAULT AS IDENTITY,
  summary     varchar(255),
  create_time datetime,
  modify_time datetime,
  PRIMARY KEY (player_id)
);
CREATE TABLE withdrawal_bill
(
  id                       bigint GENERATED BY DEFAULT AS IDENTITY,
  player_id                bigint,
  player_financial_account varchar(32),
  settle_no                varchar(32),
  amount                   numeric(18, 4),
  accounting_title         int,
  status                   varchar(16),
  player_login_account     varchar(32),
  player_name              varchar(32),
  bank_card_id             bigint,
  bank_card_no             varchar(64),
  bank_card_name           varchar(32),
  bank_name                varchar(64),
  financial_account_type   varchar(16),
  opt_man                  varchar(32),
  opt_man_id               bigint,
  create_time              datetime,
  modify_time              datetime,
  PRIMARY KEY (id)
);


CREATE INDEX order_player_id ON "order" (player_id);
CREATE INDEX player_bank_player_id ON player_bank (player_id);
CREATE INDEX player_bank_bank_id ON player_bank (bank_id);
CREATE INDEX player_financial_account_account ON player_financial_account (account);
CREATE INDEX player_financial_detail_player_financial_id ON player_financial_detail (player_financial_id);
CREATE INDEX player_financial_detail_player_financial_account ON player_financial_detail (player_financial_account);
CREATE INDEX player_financial_detail_trade_code ON player_financial_detail (trade_code);
CREATE INDEX player_lottery_trade_code ON player_lottery (trade_code);
CREATE INDEX player_lottery_player_id ON player_lottery (player_id);
CREATE INDEX player_lottery_order_id ON player_lottery (order_id);
CREATE INDEX player_lottery_handicap_id ON player_lottery (handicap_id);
CREATE INDEX player_lottery_sub_handicap_id ON player_lottery (sub_handicap_id);
CREATE INDEX player_lottery_lottery_id ON player_lottery (lottery_id);
CREATE INDEX player_lottery_play_method_id ON player_lottery (play_method_id);
CREATE INDEX player_lottery_bet_option_id ON player_lottery (bet_option_id);
CREATE INDEX player_lottery_draw_bet_option_id ON player_lottery (draw_bet_option_id);
CREATE INDEX player_lottery_draw_number ON player_lottery (draw_number);
CREATE INDEX player_lottery_combination_option_player_lottery_id ON player_lottery_combination_option (player_lottery_id);
CREATE INDEX player_lottery_combination_option_bet_option_id ON player_lottery_combination_option (bet_option_id);
CREATE INDEX player_lottery_settle_bill_trade_code ON player_lottery_settle_bill (trade_code);
CREATE INDEX player_lottery_settle_bill_player_lottery_id ON player_lottery_settle_bill (player_lottery_id);
CREATE INDEX player_lottery_settle_bill_player_id ON player_lottery_settle_bill (player_id);
CREATE INDEX player_lottery_settle_bill_player_financial_account ON player_lottery_settle_bill (player_financial_account);
CREATE INDEX withdrawal_bill_player_id ON withdrawal_bill (player_id);
CREATE INDEX withdrawal_bill_settle_no ON withdrawal_bill (settle_no);
CREATE INDEX withdrawal_bill_player_login_account ON withdrawal_bill (player_login_account);
